# -*- coding: utf-8 -*-

import sys, os
from PyQt5 import QtCore, QtGui, QtWidgets
import bow_functions as bf
import main as main_clustering

class Bow(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__(None)
        self.setObjectName("MainWindow")
        self.resize(565, 552)
        self.setWindowTitle("Language Processing")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Images/BOW.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget()
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 546, 856))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget_1 = QtWidgets.QTabWidget(self.scrollAreaWidgetContents)
        self.tabWidget_1.setObjectName("tabWidget_1")
        self.multi_file_tab = QtWidgets.QWidget()
        self.multi_file_tab.setObjectName("multi_file_tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.multi_file_tab)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.source_folder_groupBox = QtWidgets.QGroupBox(self.multi_file_tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.source_folder_groupBox.setFont(font)
        self.source_folder_groupBox.setTitle("Source folder")
        self.source_folder_groupBox.setObjectName("source_folder_groupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.source_folder_groupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.source_folder_grid = QtWidgets.QGridLayout()
        self.source_folder_grid.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.source_folder_grid.setObjectName("source_folder_grid")
        self.source_folder_line = QtWidgets.QLineEdit(self.source_folder_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.source_folder_line.sizePolicy().hasHeightForWidth())
        self.source_folder_line.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.source_folder_line.setFont(font)
        self.source_folder_line.setInputMask("")
        self.source_folder_line.setText("")
        self.source_folder_line.setObjectName("source_folder_line")
        self.source_folder_grid.addWidget(self.source_folder_line, 0, 1, 1, 1)
        self.souce_folder_browse_pushButton = QtWidgets.QPushButton(self.source_folder_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.souce_folder_browse_pushButton.sizePolicy().hasHeightForWidth())
        self.souce_folder_browse_pushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.souce_folder_browse_pushButton.setFont(font)
        self.souce_folder_browse_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.souce_folder_browse_pushButton.setText("Browse")
        self.souce_folder_browse_pushButton.setShortcut("")
        self.souce_folder_browse_pushButton.setObjectName("souce_folder_browse_pushButton")
        self.source_folder_grid.addWidget(self.souce_folder_browse_pushButton, 0, 2, 1, 1)
        self.source_folder_label = QtWidgets.QLabel(self.source_folder_groupBox)
        self.source_folder_label.setMaximumSize(QtCore.QSize(230, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.source_folder_label.setFont(font)
        self.source_folder_label.setText("Select the folder where source files are stored :")
        self.source_folder_label.setObjectName("source_folder_label")
        self.source_folder_grid.addWidget(self.source_folder_label, 0, 0, 1, 1)
        self.verticalLayout_4.addLayout(self.source_folder_grid)
        self.verticalLayout.addWidget(self.source_folder_groupBox)
        self.source_format_groupBox = QtWidgets.QGroupBox(self.multi_file_tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.source_format_groupBox.setFont(font)
        self.source_format_groupBox.setTitle("Source format")
        self.source_format_groupBox.setObjectName("source_format_groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.source_format_groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.source_format_label_1 = QtWidgets.QLabel(self.source_format_groupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.source_format_label_1.setFont(font)
        self.source_format_label_1.setText("If the source is PDF, it will beconverted to TXT and saved to a subfolder for analysis.")
        self.source_format_label_1.setWordWrap(True)
        self.source_format_label_1.setObjectName("source_format_label_1")
        self.verticalLayout_3.addWidget(self.source_format_label_1)
        self.source_format_grid = QtWidgets.QFormLayout()
        self.source_format_grid.setObjectName("source_format_grid")
        self.source_format_label_2 = QtWidgets.QLabel(self.source_format_groupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.source_format_label_2.setFont(font)
        self.source_format_label_2.setText("Select the file type of your source :")
        self.source_format_label_2.setWordWrap(False)
        self.source_format_label_2.setObjectName("source_format_label_2")
        self.source_format_grid.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.source_format_label_2)
        self.source_format_buttons = QtWidgets.QVBoxLayout()
        self.source_format_buttons.setObjectName("source_format_buttons")
        self.pdf_radioButton = QtWidgets.QRadioButton(self.source_format_groupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.pdf_radioButton.setFont(font)
        self.pdf_radioButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pdf_radioButton.setText("PDF")
        self.pdf_radioButton.setShortcut("")
        self.pdf_radioButton.setObjectName("pdf_radioButton")
        self.source_format_buttonGroup = QtWidgets.QButtonGroup()
        self.source_format_buttonGroup.setObjectName("source_format_buttonGroup")
        self.source_format_buttonGroup.addButton(self.pdf_radioButton)
        self.source_format_buttons.addWidget(self.pdf_radioButton)
        self.txt_radioButton = QtWidgets.QRadioButton(self.source_format_groupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.txt_radioButton.setFont(font)
        self.txt_radioButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.txt_radioButton.setText("TXT")
        self.txt_radioButton.setShortcut("")
        self.txt_radioButton.setObjectName("txt_radioButton")
        self.source_format_buttonGroup.addButton(self.txt_radioButton)
        self.source_format_buttons.addWidget(self.txt_radioButton)
        self.source_format_grid.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.source_format_buttons)
        self.verticalLayout_3.addLayout(self.source_format_grid)
        self.verticalLayout.addWidget(self.source_format_groupBox)
        self.dtm_groupBox = QtWidgets.QGroupBox(self.multi_file_tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.dtm_groupBox.setFont(font)
        self.dtm_groupBox.setTitle("Document Term Matrix")
        self.dtm_groupBox.setObjectName("dtm_groupBox")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.dtm_groupBox)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.dtm_label_1 = QtWidgets.QLabel(self.dtm_groupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.dtm_label_1.setFont(font)
        self.dtm_label_1.setText("All words present within the source will be saved as features and assigned a frequency per text.")
        self.dtm_label_1.setObjectName("dtm_label_1")
        self.verticalLayout_8.addWidget(self.dtm_label_1)
        self.dtm_formLayout_1 = QtWidgets.QFormLayout()
        self.dtm_formLayout_1.setObjectName("dtm_formLayout_1")
        self.dtm_label_2 = QtWidgets.QLabel(self.dtm_groupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.dtm_label_2.setFont(font)
        self.dtm_label_2.setToolTip("")
        self.dtm_label_2.setText("Choose word frequency measuring method :")
        self.dtm_label_2.setObjectName("dtm_label_2")
        self.dtm_formLayout_1.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.dtm_label_2)
        self.dtm_frequency_buttons = QtWidgets.QVBoxLayout()
        self.dtm_frequency_buttons.setObjectName("dtm_frequency_buttons")
        self.countvectorizer_radioButton = QtWidgets.QRadioButton(self.dtm_groupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.countvectorizer_radioButton.setFont(font)
        self.countvectorizer_radioButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.countvectorizer_radioButton.setText("CountVectorizer")
        self.countvectorizer_radioButton.setObjectName("countvectorizer_radioButton")
        self.vectorizer_buttonGroup = QtWidgets.QButtonGroup()
        self.vectorizer_buttonGroup.setObjectName("vectorizer_buttonGroup")
        self.vectorizer_buttonGroup.addButton(self.countvectorizer_radioButton)
        self.dtm_frequency_buttons.addWidget(self.countvectorizer_radioButton)
        self.tf_idf_radioButton = QtWidgets.QRadioButton(self.dtm_groupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.tf_idf_radioButton.setFont(font)
        self.tf_idf_radioButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tf_idf_radioButton.setText("TF - IDF")
        self.tf_idf_radioButton.setObjectName("tf_idf_radioButton")
        self.vectorizer_buttonGroup.addButton(self.tf_idf_radioButton)
        self.dtm_frequency_buttons.addWidget(self.tf_idf_radioButton)
        self.dtm_formLayout_1.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.dtm_frequency_buttons)
        self.verticalLayout_8.addLayout(self.dtm_formLayout_1)
        self.dtm_label_3 = QtWidgets.QLabel(self.dtm_groupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.dtm_label_3.setFont(font)
        self.dtm_label_3.setText("Choose minimum and maximum source frequency (proportion of files in which a feature appears) :")
        self.dtm_label_3.setObjectName("dtm_label_3")
        self.verticalLayout_8.addWidget(self.dtm_label_3)
        self.dtm_horizontalLayout = QtWidgets.QHBoxLayout()
        self.dtm_horizontalLayout.setObjectName("dtm_horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.dtm_horizontalLayout.addItem(spacerItem)
        self.dtm_frequency_spinBoxes = QtWidgets.QFormLayout()
        self.dtm_frequency_spinBoxes.setObjectName("dtm_frequency_spinBoxes")
        self.min_df_label = QtWidgets.QLabel(self.dtm_groupBox)
        self.min_df_label.setMaximumSize(QtCore.QSize(58, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.min_df_label.setFont(font)
        self.min_df_label.setText("Minimum :")
        self.min_df_label.setObjectName("min_df_label")
        self.dtm_frequency_spinBoxes.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.min_df_label)
        self.min_df_spinBox = QtWidgets.QSpinBox(self.dtm_groupBox)
        self.min_df_spinBox.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.min_df_spinBox.setFont(font)
        self.min_df_spinBox.setSuffix("%")
        self.min_df_spinBox.setMaximum(100)
        self.min_df_spinBox.setSingleStep(1)
        self.min_df_spinBox.setProperty("value", 20)
        self.min_df_spinBox.setObjectName("min_df_spinBox")
        self.dtm_frequency_spinBoxes.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.min_df_spinBox)
        self.max_df_label = QtWidgets.QLabel(self.dtm_groupBox)
        self.max_df_label.setMaximumSize(QtCore.QSize(58, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.max_df_label.setFont(font)
        self.max_df_label.setText("Maximum :")
        self.max_df_label.setObjectName("max_df_label")
        self.dtm_frequency_spinBoxes.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.max_df_label)
        self.max_df_spinBox = QtWidgets.QSpinBox(self.dtm_groupBox)
        self.max_df_spinBox.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.max_df_spinBox.setFont(font)
        self.max_df_spinBox.setSuffix("%")
        self.max_df_spinBox.setMaximum(100)
        self.max_df_spinBox.setSingleStep(1)
        self.max_df_spinBox.setProperty("value", 70)
        self.max_df_spinBox.setObjectName("max_df_spinBox")
        self.dtm_frequency_spinBoxes.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.max_df_spinBox)
        self.dtm_horizontalLayout.addLayout(self.dtm_frequency_spinBoxes)
        self.verticalLayout_8.addLayout(self.dtm_horizontalLayout)
        self.dtm_formLayout_2 = QtWidgets.QFormLayout()
        self.dtm_formLayout_2.setObjectName("dtm_formLayout_2")
        self.dtm_label_4 = QtWidgets.QLabel(self.dtm_groupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.dtm_label_4.setFont(font)
        self.dtm_label_4.setText("Choose the total number of features that will be selected for analysis :")
        self.dtm_label_4.setObjectName("dtm_label_4")
        self.dtm_formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.dtm_label_4)
        self.number_features_spinBox = QtWidgets.QSpinBox(self.dtm_groupBox)
        self.number_features_spinBox.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.number_features_spinBox.setFont(font)
        self.number_features_spinBox.setMaximum(10000)
        self.number_features_spinBox.setProperty("value", 500)
        self.number_features_spinBox.setObjectName("number_features_spinBox")
        self.dtm_formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.number_features_spinBox)
        self.verticalLayout_8.addLayout(self.dtm_formLayout_2)
        self.verticalLayout.addWidget(self.dtm_groupBox)
        self.tabWidget_2 = QtWidgets.QTabWidget(self.multi_file_tab)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.clustering_tab = QtWidgets.QWidget()
        self.clustering_tab.setObjectName("clustering_tab")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.clustering_tab)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.topic_modelling_groupBox = QtWidgets.QGroupBox(self.clustering_tab)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.topic_modelling_groupBox.setFont(font)
        self.topic_modelling_groupBox.setTitle("Topic Modelling")
        self.topic_modelling_groupBox.setObjectName("topic_modelling_groupBox")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.topic_modelling_groupBox)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.topic_modelling_label_1 = QtWidgets.QLabel(self.topic_modelling_groupBox)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.topic_modelling_label_1.setFont(font)
        self.topic_modelling_label_1.setText("The matrix will be factorised to make the most important features stand out.")
        self.topic_modelling_label_1.setObjectName("topic_modelling_label_1")
        self.verticalLayout_9.addWidget(self.topic_modelling_label_1)
        self.factorisation_formLayout = QtWidgets.QFormLayout()
        self.factorisation_formLayout.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.factorisation_formLayout.setObjectName("factorisation_formLayout")
        self.factorisation_label = QtWidgets.QLabel(self.topic_modelling_groupBox)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.factorisation_label.setFont(font)
        self.factorisation_label.setToolTip("")
        self.factorisation_label.setText("Choose matrix factorisation method :")
        self.factorisation_label.setObjectName("factorisation_label")
        self.factorisation_formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.factorisation_label)
        self.factorisation_buttons_verticalLayout = QtWidgets.QVBoxLayout()
        self.factorisation_buttons_verticalLayout.setObjectName("factorisation_buttons_verticalLayout")
        self.lda_radioButton = QtWidgets.QRadioButton(self.topic_modelling_groupBox)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lda_radioButton.setFont(font)
        self.lda_radioButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lda_radioButton.setToolTip("Latent Dirichlet Allocation")
        self.lda_radioButton.setText("LDA")
        self.lda_radioButton.setObjectName("lda_radioButton")
        self.factorisation_buttonGroup = QtWidgets.QButtonGroup()
        self.factorisation_buttonGroup.setObjectName("factorisation_buttonGroup")
        self.factorisation_buttonGroup.addButton(self.lda_radioButton)
        self.factorisation_buttons_verticalLayout.addWidget(self.lda_radioButton)
        self.nmf_radioButton = QtWidgets.QRadioButton(self.topic_modelling_groupBox)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.nmf_radioButton.setFont(font)
        self.nmf_radioButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.nmf_radioButton.setToolTip("Non-negative Matrix Factorization")
        self.nmf_radioButton.setText("NMF")
        self.nmf_radioButton.setObjectName("nmf_radioButton")
        self.factorisation_buttonGroup.addButton(self.nmf_radioButton)
        self.factorisation_buttons_verticalLayout.addWidget(self.nmf_radioButton)
        self.factorisation_formLayout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.factorisation_buttons_verticalLayout)
        self.verticalLayout_9.addLayout(self.factorisation_formLayout)
        self.topic_modelling_label_2 = QtWidgets.QLabel(self.topic_modelling_groupBox)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.topic_modelling_label_2.setFont(font)
        self.topic_modelling_label_2.setText("The features will be assembled into topics that link texts containing the same frequent features.")
        self.topic_modelling_label_2.setObjectName("topic_modelling_label_2")
        self.verticalLayout_9.addWidget(self.topic_modelling_label_2)
        self.topics_formLayout = QtWidgets.QFormLayout()
        self.topics_formLayout.setObjectName("topics_formLayout")
        self.number_topics_spinBox = QtWidgets.QSpinBox(self.topic_modelling_groupBox)
        self.number_topics_spinBox.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.number_topics_spinBox.setFont(font)
        self.number_topics_spinBox.setProperty("value", 3)
        self.number_topics_spinBox.setObjectName("number_topics_spinBox")
        self.topics_formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.number_topics_spinBox)
        self.number_top_features_label = QtWidgets.QLabel(self.topic_modelling_groupBox)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.number_top_features_label.setFont(font)
        self.number_top_features_label.setText("Choose the number of features used to describe the topics :")
        self.number_top_features_label.setObjectName("number_top_features_label")
        self.topics_formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.number_top_features_label)
        self.number_top_features_spinBox = QtWidgets.QSpinBox(self.topic_modelling_groupBox)
        self.number_top_features_spinBox.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.number_top_features_spinBox.setFont(font)
        self.number_top_features_spinBox.setProperty("value", 20)
        self.number_top_features_spinBox.setObjectName("number_top_features_spinBox")
        self.topics_formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.number_top_features_spinBox)
        self.number_topics_label = QtWidgets.QLabel(self.topic_modelling_groupBox)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.number_topics_label.setFont(font)
        self.number_topics_label.setText("Choose the number of topics that will be created :")
        self.number_topics_label.setObjectName("number_topics_label")
        self.topics_formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.number_topics_label)
        self.verticalLayout_9.addLayout(self.topics_formLayout)
        self.verticalLayout_11.addWidget(self.topic_modelling_groupBox)
        self.clustering_groupBox = QtWidgets.QGroupBox(self.clustering_tab)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.clustering_groupBox.setFont(font)
        self.clustering_groupBox.setTitle("Clustering")
        self.clustering_groupBox.setObjectName("clustering_groupBox")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.clustering_groupBox)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.clustering_label_1 = QtWidgets.QLabel(self.clustering_groupBox)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.clustering_label_1.setFont(font)
        self.clustering_label_1.setText("The texts will be separated into clusters, determined by the distance between texts (calculated from the projection of the matrix on the topics).")
        self.clustering_label_1.setWordWrap(True)
        self.clustering_label_1.setObjectName("clustering_label_1")
        self.verticalLayout_10.addWidget(self.clustering_label_1)
        self.number_clusters_formLayout = QtWidgets.QFormLayout()
        self.number_clusters_formLayout.setObjectName("number_clusters_formLayout")
        self.number_clusters_label = QtWidgets.QLabel(self.clustering_groupBox)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.number_clusters_label.setFont(font)
        self.number_clusters_label.setText("Choose the number k of clusters that will be created :")
        self.number_clusters_label.setObjectName("number_clusters_label")
        self.number_clusters_formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.number_clusters_label)
        self.number_clusters_spinBox = QtWidgets.QSpinBox(self.clustering_groupBox)
        self.number_clusters_spinBox.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.number_clusters_spinBox.setFont(font)
        self.number_clusters_spinBox.setProperty("value", 3)
        self.number_clusters_spinBox.setObjectName("number_clusters_spinBox")
        self.number_clusters_formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.number_clusters_spinBox)
        self.verticalLayout_10.addLayout(self.number_clusters_formLayout)
        self.clustering_label_2 = QtWidgets.QLabel(self.clustering_groupBox)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.clustering_label_2.setFont(font)
        self.clustering_label_2.setText("Economic data will be computed to compare a priori analysis with realisation.")
        self.clustering_label_2.setObjectName("clustering_label_2")
        self.verticalLayout_10.addWidget(self.clustering_label_2)
        self.display_clusters_horizontalLayout = QtWidgets.QHBoxLayout()
        self.display_clusters_horizontalLayout.setObjectName("display_clusters_horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.display_clusters_horizontalLayout.addItem(spacerItem1)
        self.display_clusters_checkBox = QtWidgets.QCheckBox(self.clustering_groupBox)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.display_clusters_checkBox.setFont(font)
        self.display_clusters_checkBox.setText("Display economic data clusters")
        self.display_clusters_checkBox.setObjectName("display_clusters_checkBox")
        self.display_clusters_horizontalLayout.addWidget(self.display_clusters_checkBox)
        self.verticalLayout_10.addLayout(self.display_clusters_horizontalLayout)
        self.verticalLayout_11.addWidget(self.clustering_groupBox)
        spacerItem2 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem2)
        self.start_clustering_pushButton = QtWidgets.QPushButton(self.clustering_tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.start_clustering_pushButton.setFont(font)
        self.start_clustering_pushButton.setText("Start clustering")
        self.start_clustering_pushButton.setObjectName("start_clustering_pushButton")
        self.verticalLayout_11.addWidget(self.start_clustering_pushButton)
        spacerItem3 = QtWidgets.QSpacerItem(20, 2, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem3)
        self.tabWidget_2.addTab(self.clustering_tab, "Clustering")
        self.text_to_text_distance_tab = QtWidgets.QWidget()
        self.text_to_text_distance_tab.setObjectName("text_to_text_distance_tab")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.text_to_text_distance_tab)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.distances_groupBox = QtWidgets.QGroupBox(self.text_to_text_distance_tab)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.distances_groupBox.setFont(font)
        self.distances_groupBox.setTitle("Text-to-text distances")
        self.distances_groupBox.setObjectName("distances_groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.distances_groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.distances_label_1 = QtWidgets.QLabel(self.distances_groupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.distances_label_1.setFont(font)
        self.distances_label_1.setText("Although the euclidian distance is mandatory for the clustering, the distance function for the text-to-text distance computation can be freely selected.")
        self.distances_label_1.setWordWrap(True)
        self.distances_label_1.setObjectName("distances_label_1")
        self.gridLayout_3.addWidget(self.distances_label_1, 0, 0, 1, 1)
        self.distance_function_formLayout = QtWidgets.QFormLayout()
        self.distance_function_formLayout.setObjectName("distance_function_formLayout")
        self.distance_function_label = QtWidgets.QLabel(self.distances_groupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.distance_function_label.setFont(font)
        self.distance_function_label.setText("Choose  distance function : ")
        self.distance_function_label.setObjectName("distance_function_label")
        self.distance_function_formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.distance_function_label)
        self.distance_function_buttons = QtWidgets.QVBoxLayout()
        self.distance_function_buttons.setObjectName("distance_function_buttons")
        self.euclidian_radioButton = QtWidgets.QRadioButton(self.distances_groupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.euclidian_radioButton.setFont(font)
        self.euclidian_radioButton.setText("Euclidian")
        self.euclidian_radioButton.setObjectName("euclidian_radioButton")
        self.distance_function_buttonGroup = QtWidgets.QButtonGroup()
        self.distance_function_buttonGroup.setObjectName("distance_function_buttonGroup")
        self.distance_function_buttonGroup.addButton(self.euclidian_radioButton)
        self.distance_function_buttons.addWidget(self.euclidian_radioButton)
        self.cos_similarity_radioButton = QtWidgets.QRadioButton(self.distances_groupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.cos_similarity_radioButton.setFont(font)
        self.cos_similarity_radioButton.setText("Cos-similarity")
        self.cos_similarity_radioButton.setObjectName("cos_similarity_radioButton")
        self.distance_function_buttonGroup.addButton(self.cos_similarity_radioButton)
        self.distance_function_buttons.addWidget(self.cos_similarity_radioButton)
        self.distance_function_formLayout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.distance_function_buttons)
        self.gridLayout_3.addLayout(self.distance_function_formLayout, 1, 0, 1, 1)
        self.distances_label_2 = QtWidgets.QLabel(self.distances_groupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.distances_label_2.setFont(font)
        self.distances_label_2.setText("The vectors will be projected in a space fit for visualisation.")
        self.distances_label_2.setObjectName("distances_label_2")
        self.gridLayout_3.addWidget(self.distances_label_2, 2, 0, 1, 1)
        self.dimension_formLayout = QtWidgets.QFormLayout()
        self.dimension_formLayout.setObjectName("dimension_formLayout")
        self.dimension_label = QtWidgets.QLabel(self.distances_groupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.dimension_label.setFont(font)
        self.dimension_label.setText("Choose visualisation dimension : ")
        self.dimension_label.setObjectName("dimension_label")
        self.dimension_formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.dimension_label)
        self.dimension_buttons = QtWidgets.QVBoxLayout()
        self.dimension_buttons.setObjectName("dimension_buttons")
        self.dimension2_radioButton = QtWidgets.QRadioButton(self.distances_groupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.dimension2_radioButton.setFont(font)
        self.dimension2_radioButton.setText("2D")
        self.dimension2_radioButton.setObjectName("dimension2_radioButton")
        self.dimension_buttonGroup = QtWidgets.QButtonGroup()
        self.dimension_buttonGroup.setObjectName("dimension_buttonGroup")
        self.dimension_buttonGroup.addButton(self.dimension2_radioButton)
        self.dimension_buttons.addWidget(self.dimension2_radioButton)
        self.dimension3_radioButton = QtWidgets.QRadioButton(self.distances_groupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.dimension3_radioButton.setFont(font)
        self.dimension3_radioButton.setText("3D")
        self.dimension3_radioButton.setObjectName("dimension3_radioButton")
        self.dimension_buttonGroup.addButton(self.dimension3_radioButton)
        self.dimension_buttons.addWidget(self.dimension3_radioButton)
        self.dimension_formLayout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.dimension_buttons)
        self.gridLayout_3.addLayout(self.dimension_formLayout, 3, 0, 1, 1)
        self.verticalLayout_12.addWidget(self.distances_groupBox)
        spacerItem4 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_12.addItem(spacerItem4)
        self.compute_distances_pushButton = QtWidgets.QPushButton(self.text_to_text_distance_tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.compute_distances_pushButton.setFont(font)
        self.compute_distances_pushButton.setText("Compute distances")
        self.compute_distances_pushButton.setObjectName("compute_distances_pushButton")
        self.verticalLayout_12.addWidget(self.compute_distances_pushButton)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem5)
        self.tabWidget_2.addTab(self.text_to_text_distance_tab, "Text-to-text distances")
        self.verticalLayout.addWidget(self.tabWidget_2)
        self.tabWidget_1.addTab(self.multi_file_tab, "Multi-file")
        self.single_file_tab = QtWidgets.QWidget()
        self.single_file_tab.setObjectName("single_file_tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.single_file_tab)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.source_file_groupBox = QtWidgets.QGroupBox(self.single_file_tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.source_file_groupBox.setFont(font)
        self.source_file_groupBox.setTitle("Source file")
        self.source_file_groupBox.setObjectName("source_file_groupBox")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.source_file_groupBox)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.source_file_label_1 = QtWidgets.QLabel(self.source_file_groupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.source_file_label_1.setFont(font)
        self.source_file_label_1.setText("If the source file is PDF, it will be converted to TXT and saved to a subfolder before analysis.")
        self.source_file_label_1.setObjectName("source_file_label_1")
        self.verticalLayout_6.addWidget(self.source_file_label_1)
        self.source_file_grid = QtWidgets.QGridLayout()
        self.source_file_grid.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.source_file_grid.setObjectName("source_file_grid")
        self.source_file_line = QtWidgets.QLineEdit(self.source_file_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.source_file_line.sizePolicy().hasHeightForWidth())
        self.source_file_line.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.source_file_line.setFont(font)
        self.source_file_line.setInputMask("")
        self.source_file_line.setText("")
        self.source_file_line.setObjectName("source_file_line")
        self.source_file_grid.addWidget(self.source_file_line, 0, 1, 1, 1)
        self.source_file_browse_pushButton = QtWidgets.QPushButton(self.source_file_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.source_file_browse_pushButton.sizePolicy().hasHeightForWidth())
        self.source_file_browse_pushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.source_file_browse_pushButton.setFont(font)
        self.source_file_browse_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.source_file_browse_pushButton.setText("Browse")
        self.source_file_browse_pushButton.setShortcut("")
        self.source_file_browse_pushButton.setObjectName("source_file_browse_pushButton")
        self.source_file_grid.addWidget(self.source_file_browse_pushButton, 0, 2, 1, 1)
        self.source_file_label_2 = QtWidgets.QLabel(self.source_file_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.source_file_label_2.sizePolicy().hasHeightForWidth())
        self.source_file_label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.source_file_label_2.setFont(font)
        self.source_file_label_2.setText("Select  source file :")
        self.source_file_label_2.setObjectName("source_file_label_2")
        self.source_file_grid.addWidget(self.source_file_label_2, 0, 0, 1, 1)
        self.verticalLayout_6.addLayout(self.source_file_grid)
        self.verticalLayout_2.addWidget(self.source_file_groupBox)
        self.parameters_groupBox = QtWidgets.QGroupBox(self.single_file_tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.parameters_groupBox.setFont(font)
        self.parameters_groupBox.setTitle("Parameters")
        self.parameters_groupBox.setObjectName("parameters_groupBox")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.parameters_groupBox)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.number_nltk_features_layout = QtWidgets.QFormLayout()
        self.number_nltk_features_layout.setObjectName("number_nltk_features_layout")
        self.number_nltk_features_label = QtWidgets.QLabel(self.parameters_groupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.number_nltk_features_label.setFont(font)
        self.number_nltk_features_label.setText("Select the number of features to display :")
        self.number_nltk_features_label.setObjectName("number_nltk_features_label")
        self.number_nltk_features_layout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.number_nltk_features_label)
        self.number_nltk_features_spinBox = QtWidgets.QSpinBox(self.parameters_groupBox)
        self.number_nltk_features_spinBox.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.number_nltk_features_spinBox.setFont(font)
        self.number_nltk_features_spinBox.setMinimum(20)
        self.number_nltk_features_spinBox.setMaximum(150)
        self.number_nltk_features_spinBox.setProperty("value", 50)
        self.number_nltk_features_spinBox.setObjectName("number_nltk_features_spinBox")
        self.number_nltk_features_layout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.number_nltk_features_spinBox)
        self.verticalLayout_5.addLayout(self.number_nltk_features_layout)
        self.stemming_formLayout = QtWidgets.QFormLayout()
        self.stemming_formLayout.setObjectName("stemming_formLayout")
        self.stemming_label = QtWidgets.QLabel(self.parameters_groupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.stemming_label.setFont(font)
        self.stemming_label.setText("Check this box if you want to perform a stemming before analysis :")
        self.stemming_label.setObjectName("stemming_label")
        self.stemming_formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.stemming_label)
        self.stemming_checkBox = QtWidgets.QCheckBox(self.parameters_groupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.stemming_checkBox.setFont(font)
        self.stemming_checkBox.setText("Stem words")
        self.stemming_checkBox.setObjectName("stemming_checkBox")
        self.stemming_formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.stemming_checkBox)
        self.verticalLayout_5.addLayout(self.stemming_formLayout)
        self.verticalLayout_2.addWidget(self.parameters_groupBox)
        spacerItem6 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem6)
        self.compute_top_features_pushButton = QtWidgets.QPushButton(self.single_file_tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.compute_top_features_pushButton.setFont(font)
        self.compute_top_features_pushButton.setText("Compute top features")
        self.compute_top_features_pushButton.setObjectName("compute_top_features_pushButton")
        self.verticalLayout_2.addWidget(self.compute_top_features_pushButton)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem7)
        self.tabWidget_1.addTab(self.single_file_tab, "Single file")
        self.gridLayout_2.addWidget(self.tabWidget_1, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar()
        self.menubar.setGeometry(QtCore.QRect(0, 0, 565, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setTitle("File")
        self.menuFile.setObjectName("menuFile")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setTitle("?")
        self.menuAbout.setObjectName("menuAbout")
        self.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar()
        self.statusbar.setObjectName("statusbar")
        self.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(self)
        self.actionExit.setText("Exit")
        self.actionExit.setObjectName("actionExit")
        self.actionAbout = QtWidgets.QAction(self)
        self.actionAbout.setText("About")
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionExit)
        self.menuAbout.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.tabWidget_1.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)

###################   END OF QT OUTPUT  ###########################

        #Action menus
        self.actionExit.triggered.connect(self.exit_program)
        self.actionAbout.triggered.connect(self.about_dialog)

        #Browse windows
        self.souce_folder_browse_pushButton.clicked.connect(self.folder_path_dialog)
        self.source_file_browse_pushButton.clicked.connect(self.file_path_dialog)

        #Default toggled radio buttons
        self.pdf_radioButton.toggle()
        self.countvectorizer_radioButton.toggle()
        self.lda_radioButton.toggle()
        self.euclidian_radioButton.toggle()
        self.dimension2_radioButton.toggle()

        #Start buttons
        self.start_clustering_pushButton.clicked.connect(self.start_clustering)
        self.compute_distances_pushButton.clicked.connect(self.compute_distances)
        self.compute_top_features_pushButton.clicked.connect(self.compute_top_features)


    def exit_program(self):
        exit_message = QtWidgets.QMessageBox()
        exit_message.setWindowTitle("Exit program")
        exit_message.setText("Any changes made will be discarded.\nDo you want to proceed ?")
        exit_message.addButton(QtWidgets.QMessageBox.Yes)
        exit_message.addButton(QtWidgets.QMessageBox.No)
        if (exit_message.exec_() == QtWidgets.QMessageBox.Yes):
            self.close()


    def about_dialog(self):
        message = QtWidgets.QMessageBox()
        message.setWindowTitle("About")
        message.setText("ENPC 2016-2017\nProjet TDLOG\n"
                        "\nFrançois DUPRÉ\nPierre GIACCOBI\nPierre LECUYER\nFlorian MANTE")
        message.exec_()


    def folder_path_dialog(self):
        options = QtWidgets.QFileDialog.Options()
        self.source_folder_line.setText(str(QtWidgets.QFileDialog.getExistingDirectory(self,
                                                                                       "Choose source folder", "",
                                                                                       options=options)))


    def file_path_dialog(self):
        options = QtWidgets.QFileDialog.Options()
        self.source_file_line.setText(str(QtWidgets.QFileDialog.getOpenFileName(self,
                                                                                "Choose source file", "",
                                                                                options=options)[0]))


    def start_clustering(self):
        self.folder_path = self.source_folder_line.text()
        # fetch parameters
        self.format = self.source_format_buttonGroup.checkedButton().text().lower()

        self.input_techniques = {"Vectorize": self.vectorizer_buttonGroup.checkedButton().text(),
                                 "Factor": self.factorisation_buttonGroup.checkedButton().text()}

        self.input_param = {'Vectorizer':
                                {'input': 'filename',
                                 'max_features' : self.number_features_spinBox.value(),
                                 'max_df': self.max_df_spinBox.value() / 100,
                                 'min_df': self.min_df_spinBox.value() / 100},
                            'NMF':
                                {'n_components': self.number_topics_spinBox.value()},
                            'LDA':
                                {'n_topics': self.number_topics_spinBox.value()},
                            'k-Means':
                                {'init': 'k-means++',
                                 'n_clusters': self.number_clusters_spinBox.value(),
                                 'n_init': 10},
                            'display':
                                {'most_important' : self.number_top_features_spinBox.value()}}

        # Launch or error message
        valid, error_message_text = bf.valid_start_clustering(self)

        if valid:
            # if self.format == "pdf":
            #     bf.convert_pdf(self)
            #     self.folder_path += "/converted"
            #
            # os.chdir(self.folder_path)
            # self.input_files = [file for file in os.listdir() if file.endswith(".txt")]

            main_clustering.main_clustering(self)
            # TODO : access algorithm from here
            # output = algorithm(parameters, files)


        else:
            error_message = QtWidgets.QMessageBox()
            error_message.setWindowTitle("Error")
            error_message.setText(error_message_text)
            error_message.exec_()


    def compute_distances(self):
        pass


    def compute_top_features(self):
        pass


if __name__ == '__main__':
    bow_gui = QtWidgets.QApplication(sys.argv)
    mainWindow = Bow()
    mainWindow.show()
    mainWindow.raise_()
    bow_gui.exec_()